import React, { useState } from 'react'

export default function ExportButton({ analysisData }) {
  const [copied, setCopied] = useState(false)

  if (!analysisData) return null

  const generateTextReport = () => {
    const d = analysisData
    let text = `SPECTRALENS FIELD HEALTH REPORT\n`
    text += `${'='.repeat(40)}\n\n`
    text += `EXECUTIVE SUMMARY\n${d.executive_summary}\n\n`
    text += `OVERALL FIELD HEALTH: ${d.overall_field_health}%\n`
    text += `CONFIDENCE: ${d.confidence}\n\n`
    text += `ZONE ANALYSIS\n${'-'.repeat(30)}\n`
    for (const zone of d.zones || []) {
      text += `\n${zone.name}\n`
      text += `  Status: ${zone.health_status} (${zone.severity})\n`
      text += `  NDVI: ${zone.ndvi}\n`
      text += `  Finding: ${zone.finding}\n`
      text += `  Action: ${zone.recommendation}\n`
    }
    text += `\nIMMEDIATE ACTIONS\n${'-'.repeat(30)}\n`
    for (const [i, action] of (d.immediate_actions || []).entries()) {
      text += `${i + 1}. ${action}\n`
    }
    text += `\nESTIMATED YIELD IMPACT: ${d.estimated_yield_impact}\n`
    text += `NEXT SCAN: ${d.next_scan_recommendation}\n\n`
    text += `Generated by SpectraLens AI\n`
    return text
  }

  const handleDownload = () => {
    const text = generateTextReport()
    const blob = new Blob([text], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'spectralens-report.txt'
    a.click()
    URL.revokeObjectURL(url)
  }

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(analysisData.executive_summary)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Fallback
      const el = document.createElement('textarea')
      el.value = analysisData.executive_summary
      document.body.appendChild(el)
      el.select()
      document.execCommand('copy')
      document.body.removeChild(el)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  return (
    <div className="flex gap-2 pt-3 border-t border-slate-200">
      <button
        onClick={handleDownload}
        className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-brand rounded-lg hover:bg-brand-light transition-colors"
      >
        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
        </svg>
        Download Report
      </button>
      <button
        onClick={handleCopy}
        className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-slate-600 border border-slate-200 rounded-lg hover:bg-slate-50 transition-colors"
      >
        {copied ? (
          <>
            <svg className="w-4 h-4 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
            </svg>
            Copied!
          </>
        ) : (
          <>
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M15.666 3.888A2.25 2.25 0 0013.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 01-.75.75H9.75a.75.75 0 01-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 01-2.25 2.25H6.75A2.25 2.25 0 014.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 011.927-.184" />
            </svg>
            Copy Summary
          </>
        )}
      </button>
    </div>
  )
}
